/*
  Warnings:

  - You are about to drop the `usuario` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE `usuario`;

-- CreateTable
CREATE TABLE `user` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `user_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `banana` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NRORDPROD` VARCHAR(191) NOT NULL,
    `CODFICHA` VARCHAR(191) NOT NULL,
    `CODCMFICHA` VARCHAR(191) NULL,
    `NOMEFICHA` VARCHAR(191) NULL,
    `UNIDMEDFICHA` VARCHAR(191) NULL,
    `DATAGERACAOOP` DATETIME(3) NOT NULL,
    `DATAINICIO` DATETIME(3) NULL,
    `DATAFINAL` DATETIME(3) NULL,
    `QTDPLANEJADA` DOUBLE NOT NULL,
    `RENDIMENTO` DOUBLE NULL,
    `NRRETEST` VARCHAR(191) NULL,
    `NRLANCESTQ` VARCHAR(191) NULL,
    `CDSETOR` VARCHAR(191) NULL,
    `CDCENTCUST` VARCHAR(191) NULL,
    `NRSEQRETPROD` VARCHAR(191) NULL,
    `CODITEM` VARCHAR(191) NULL,
    `INSUMO` VARCHAR(191) NULL,
    `CODCM` VARCHAR(191) NULL,
    `UNIDMED` VARCHAR(191) NULL,
    `VRPESOUNID` DOUBLE NULL,
    `PRODSUBSTITUIDO` VARCHAR(191) NULL,
    `QTDPREVISTA` DOUBLE NULL,
    `DSLANCESTIT` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
